# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.1.3

    working_directory: ~/hapi-cli

    steps:
      - checkout

      # Download and cache dependencies
      - run: npm install
      - run: sudo npm install nyc mocha chai chai-json-schema chai-fs -g

      # run tests!
      - run: npm test


